### ISSUE TITLE
Martin Schultz: “Machine learning for weather, air quality and climate”

### ISSUE THREAD

**Issue by fiatxlux** [Nowosad/OGH_summer_school_2022#1]
Hi there, workshop materials for Martin Schultz: “Machine learning for weather, air quality and climate” are inaccessible. Are they supposed to be open? thanks

**Comment by Nowosad** [comment]
Hi @fiatxlux -- I can access them:

![image](https://user-images.githubusercontent.com/3457131/188812020-6d13eec9-71c9-44b9-9cb1-e3df52f20cc2.png)

Have you tried using different browser or internet provider?

**Comment by fiatxlux** [comment]
Thanks. I have tried 3 different providers.

**Comment by maschu09** [comment]
We had a power outage due to a thunderstorm last night. Please try again - the slides should be openly accessible.
